site_name: infra-lab
site_author: riupie maintainers
site_url: https://riupie.com/infra-lab/
repo_name: riupie/infra-lab
repo_url: https://github.com/riupie/infra-lab

docs_dir: .

nav:
  - Getting Started:
    - README.md
    - Lab Architecture: docs/getting-started/lab-architecture.md

theme:
  name: material
  #custom_dir: docs/overrides
  features:
    - content.code.annotate
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky

extra:
  version:
    provider: mike
extra_css:
  - docs/stylesheets/extra.css

markdown_extensions:
  - meta
  - tables
  - toc:
      permalink: true
  - abbr
  - extra
  - admonition
  - smarty
  - sane_lists
  - nl2br
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - same-dir
  - search
  - literate-nav
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true