---
- name: Generate /etc/hosts for all of the nodes
  hosts: all
  become: true
  gather_facts: true
  vars:
    cluster_storage_interface: "eth1"
    public_storage_interface: "eth0"

  tasks:
    - name: Generate /etc/hosts for all of the nodes
      blockinfile:
        dest: /etc/hosts
        marker: "# {mark} ANSIBLE CEPH STORAGE GENERATED HOSTS"
        block: |
          {% for item in play_hosts %}
          {{ hostvars[item]['ansible_' ~ cluster_storage_interface]['ipv4']['address'] }} {{ hostvars[item]['ansible_hostname'] }}.private.lab.riupie.com {{ hostvars[item]['ansible_hostname'] }}
          {{ hostvars[item]['ansible_' ~ public_storage_interface]['ipv4']['address'] }} {{ hostvars[item]['ansible_hostname'] }}.public.lab.riupie.com
          {% endfor %}

